name: CI/CD - React App + NPM Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # ===============================
  #  JOB 1 BUILD & TEST
  # ===============================
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Tests
      - name: Run tests
        run: pnpm test
        working-directory: my-app

      # Build React
      - name: Build React app
        run: pnpm build
        working-directory: my-app



  # ===============================
  #  JOB 2 -  PUBLISH NPM
  # ===============================
  publish-npm:
    name: Publish to NPM
    needs: build_test
    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.version_check.outputs.published }}

    steps:
      - uses: actions/checkout@v4

      # Install pnpm (OBLIGATOIRE)
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check version difference
        id: version_check
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          REMOTE_VERSION=$(npm view $PACKAGE_NAME version 2>/dev/null || echo "0.0.0")

          echo "Local: $LOCAL_VERSION"
          echo "Remote: $REMOTE_VERSION"

          if [ "$LOCAL_VERSION" != "$REMOTE_VERSION" ]; then
            echo "published=true" >> $GITHUB_OUTPUT
          else
            echo "published=false" >> $GITHUB_OUTPUT
          fi

      - name: Build library
        if: steps.version_check.outputs.published == 'true'
        run: pnpm run build-npm-ci

      # Publish
      - name: Publish to NPM
        if: steps.version_check.outputs.published == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Skip message
      - name: Skip publish
        if: steps.version_check.outputs.published == 'false'
        run: echo "Version unchanged — skipping publish."


  # ===============================
  # JOB 3 - DEPLOY
  # ===============================
  deploy:
    name: Deploy to GitHub Pages
    needs: publish-npm
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - uses: actions/deploy-pages@v4